Adding visualization - tensorboard, accuracy-score, confusion-matrix for Cifar 10 Example
chauhang/pytorch-pipeline pull request #11
Opened 2021-04-13 18:41 UTC by shrinath-suresh

Signed-off-by: Shrinath Suresh <shrinath@ideas2it.com>

2021-04-15 02:57 UTC, chauhang commented on cifar10/utils.py
> +        s3_resource = boto3.resource("s3")
@shrinath-suresh Can we remove dependency on boto / s3 and use pvc/volumes instead?

2021-04-15 02:58 UTC, chauhang commented on cifar10/pipeline.py
> +        input_parameters = [{"tensorboard_root": "s3://kubeflow-dataset/tensorboardX",
@shrinath-suresh Please remove the dependency on S3

2021-04-15 03:00 UTC, chauhang commented on cifar10/pipeline.py
> +        source_code = ["https://kubeflow-dataset.s3.us-east-2.amazonaws.com/cifar10_datamodule.py", "https://kubeflow-dataset.s3.us-east-2.amazonaws.com/cifar10_train.py", "https://kubeflow-dataset.s
@shrinath-suresh Please use the git url instead, remove dependency on s3

2021-04-15 03:01 UTC, chauhang requested changes
Please see comments inline for s3 dependencies in the code

2021-05-19 18:03 UTC, shrinath-suresh commented
Duplicate. Merged using the following PRs https://github.com/chauhang/pytorch-pipeline/pull/19 and https://github.com/chauhang/pytorch-pipeline/pull/17

2021-05-19 18:03 UTC, closed without merging