[WIP] Fix base classes
chauhang/pytorch-pipeline pull request #36
Opened 2021-05-28 19:45 UTC by shrinath-suresh

This PR contains the updated base component and base executor classes

2021-05-28 19:57 UTC, shrinath-suresh commented on pytorch_pipeline/components/trainer/component.py
> +            # self.ptl_trainer = Executor().Do(
working on executor restructuring. will enable this once the restructuring is done.

2021-05-31 04:32 UTC, chauhang commented on pytorch_pipeline/components/trainer/component.py
> -        if not module_file:
@shrinath-suresh How is the actual input validations going to happen after the code structure change? In the new logic there is no validation check for the Trainer specific parameters.

2021-05-31 04:32 UTC, chauhang commented on pytorch_pipeline/components/trainer/component.py
> -        if not data_module_file:
@shrinath-suresh Same as above

2021-05-31 04:34 UTC, chauhang requested changes
Please see the review comments

2021-05-31 15:11 UTC, shrinath-suresh commented
@ankan94 @chauhang Lets continue the changes in the following PR - https://github.com/chauhang/pytorch-pipeline/pull/37 . Closing this PR to avoid confusions.

2021-05-31 15:11 UTC, closed without merging